<?php

namespace Epsi\PremierBundle\Repository;

/**
 * EntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntrepriseRepository extends \Doctrine\ORM\EntityRepository
{
    public function deleteEntreprise($id)
    {
        $r=$this->_em
        ->createQueryBuilder()
        ->delete($this->_entityName, 'c')
        ->where('c.id = :categorie_id')
        ->setParameter('categorie_id', $id)
        ->getQuery();
 
 return 1 === $r->getScalarResult();
    }
}
