<?php

namespace Epsi\PremierBundle\Repository;

/**
 * ListeMotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeMotRepository extends \Doctrine\ORM\EntityRepository
{
}
