<?php

namespace Epsi\PremierBundle\Repository;

/**
 * listeMotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class listeMotRepository extends \Doctrine\ORM\EntityRepository
{
}
