<?php

namespace Epsi\PremierBundle\Repository;

/**
 * MotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotRepository extends \Doctrine\ORM\EntityRepository
{
}
