<?php

namespace Epsi\PremierBundle\Repository;

/**
 * TestUtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestUtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
